iiname: 'SSH4Me'
author: 'jisan09'
description: 'Build SSH tunnel using ngrok over workflow'
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
runs:
  using: 'composite'
  steps:
    - name: 'Set up Docker'
      shell: bash
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh

    - name: 'Build Docker image'
      shell: bash
      run: |
         

     run: |
        docker build -t ssh4me --build-arg AUTH_TOKEN=$AUTH_TOKEN --build-arg PASSWORD=$PASSWORD .
    - name: 'Run Docker container'
      shell: bash
      run: docker run-it --cache-from type=gha,mode=max --cache-to type=gha,mode=max docker.io/library/ssh4me 
  
      with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
branding:
  icon: 'terminal'
  color: 'gray-dark'
